name: docker-stable-diffusion
services:
  stable-diffusion:
    container_name: stable-diffusion
    tty: true
    build:
      context: ./stable-diffusion
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./models
        target: /app/models
      - type: bind
        source: ./outputs
        target: /app/outputs
      - type: bind
        source: ./src
        target: /app/src
      - type: volume
        source: cache
        target: /app/cache
    environment:
      TZ: Asia/Tokyo
      TRANSFORMERS_CACHE: /app/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
              capabilities:
                - compute
                - utility
volumes:
  cache:
    name: cache
    driver: local
